### ISSUE TITLE
Geometry of the models

### ISSUE THREAD

**Issue by Sh4dySh4d** [leeao/Noesis-Plugins#2]
Hello, first of all, I wanted to say you made an impressive work on that plugin, however the only issue I have with it, I don't know if this is normal or not, but the models come out like this, the MK ones
![image](https://user-images.githubusercontent.com/84101875/118039790-19183980-b347-11eb-9f82-3d3a65db9319.png)

**Comment by leeao** [comment]
Yes, I know the problem. The map model uses other vertex index storage methods. I have tried to solve it, but there is no progress.

**Comment by leeao** [comment]
Regarding the script update for Mortal Kombat PS2 to add weights support , stage and konquest support, please move here:
https://github.com/leeao/MortalKombat
