### ISSUE TITLE
MKD-MKA Konquest Characters Models

### ISSUE THREAD

**Issue by 972oTeV** [leeao/Noesis-Plugins#3]
Hi, Thanks a lot For the Script!! 😄 

Well, The problem is: 
I can't load chars from the Konquest mode in noesis
No one from MKD (i'm really interested in those ones) 
But some from MKA, i mean the ones who are dismembered in the game, (by fatality or sword blows), but not the normal version of those enemies (in one piece or some enemy like a yeti), Or some principal character, like taven, subzero etc.

Enemy from MKA, normal version won't open, Cut Version yes.
![Screenshot_6](https://user-images.githubusercontent.com/122237320/211224208-b03f634c-c075-4af1-ab5a-f15ac7eec8a7.jpg)
Special Chars opened, but aren't cut (idk if it's related)
![Screenshot_8](https://user-images.githubusercontent.com/122237320/211224249-213fc91c-3a00-4668-b4a1-50304ca7438e.jpg)
Char from Konquest MKD, won't open:
![Screenshot_9](https://user-images.githubusercontent.com/122237320/211224300-2ce8985c-00ac-457a-95ca-d60ec0ca3e48.jpg)

I already read the others issue, and of course will be awesome if the Konquest models come with weights, but if i can get the model in T pose, later i can add weights with blender, i can do that.

But if you are interested, there are another way to extract models (fighters from mkda,mka) with weights, but with wrong named vertex groups, it's an script for a version of blender, but maybe you can find something useful there in the script 😃
https://zenhax.com/viewtopic.php?t=2265
(With that, i can opened the Yeti mentioned before, but won't work with chars from mkd)
Thanks Anyway :)

**Comment by leeao** [comment]
Can you provide some samples?
At present, I have already fixed the weight of PS2 versions of MKDA, MKD and MKA.
In addition, support has been added for the PS2 stage model.
It's just not perfect yet. I haven't decided to release it.
The formats of MKDA and MKD/MKA are different. MKDA does not use native PS2 geometry.
However, their skin bone index has also been secretly adjusted, especially the PS2 version, which took me a long time to discover.
The new version also adds support for the MKU PSP version.

**Comment by 972oTeV** [comment]
> Can you provide some samples? At present, I have already fixed the weight of PS2 versions of MKDA, MKD and MKA. In addition, support has been added for the PS2 stage model. It's just not perfect yet. I haven't decided to release it. The formats of MKDA and MKD/MKA are different. MKDA does not use native PS2 geometry. However, their skin bone index has also been secretly adjusted, especially the PS2 version, which took me a long time to discover. The new version also adds support for the MKU PSP version.

oh yeah, sure:
https://mega.nz/file/4xginByb#y73WnHcaJWcdUU-IWAJe01GSNw_vZeVXDwbFK53XKLM
mka and mkd, i don't have mkda, but there are konquest models, fighters, items (and 2 dead soldiers), some from motor kombat, and 1 map from each game, if you need something more tell me 😄
Also there's the program sffexplorer 👍 
Thanks for the Reply ad the info, See ya :)

**Comment by 972oTeV** [comment]
hi @leeao, some update?
![zoom gato](https://user-images.githubusercontent.com/122237320/212788284-7d4ce9a9-9ee7-47c0-88a6-8aadb3cbc8dc.jpg)
Sorry for the tag, but i want to know 😄

**Comment by 972oTeV** [comment]
Hi @leeao  , are you ok? 
i left the samples like a month ago, but you don't reply, 
maybe if you update the script to the one you have now, i can check the models for myself. 

Sorry for bother.

**Comment by CactusBack** [comment]
Any chance for an update to this? I'm also trying to extract Konquest models with no success.

**Comment by 972oTeV** [comment]
@CactusBack 
nothing happens from january, idk if the guy still alive :(
About Konquest depending from where, from mka it's posible (with an specific blender or with the ermaccer tool) but without weights, but i have no luck with the MKD models (fighters and konquest)

**Comment by CactusBack** [comment]
@972oTeV ah that's a shame about MKD models.

Hopefully leeao is okay and comes back to this one day.

**Comment by leeao** [comment]
Hello guys!
Regarding the script update for Mortal Kombat PS2 to add weights support and konquest support, please move here:
https://github.com/leeao/MortalKombat

**Comment by CactusBack** [comment]
@leeao that's amazing! I've just tested the new version with a few MKD and MKA Konquest models. They seem to work great now. Thank you so much for this!
