### ISSUE TITLE
Ps2 Import error

### ISSUE THREAD

**Issue by ran-j** [leeao/Noesis-Plugins#4]
Hey there amazing plugin.

Can you help me import  PS2 game Shijyou Saikyou no Deshi Kenichi - Gekitou! Ragnarok Hachikengou.

When I try to import the dff model i got this error:

![image](https://github.com/leeao/Noesis-Plugins/assets/17410205/75a92671-d43b-48e9-8b22-b777f08cf6bb)

Looking at RW Analyze looks like to be a valid file 

![image](https://github.com/leeao/Noesis-Plugins/assets/17410205/1406d443-591e-4472-aa8e-da6b3d01b183)

Here is the source model: https://drive.google.com/drive/folders/13Wwkr_ceYsCrMtqopm13JRtIHihxwtw8?usp=sharing

**Comment by ran-j** [comment]
![image](https://github.com/leeao/Noesis-Plugins/assets/17410205/373a57ed-bbae-4001-af1e-68ea5911a9d8)

If I ignore thouse error I cant load the model

**Comment by leeao** [comment]
Updated. Check for the latest script.
![未命名1687577967](https://github.com/leeao/Noesis-Plugins/assets/15622541/b6bed20e-e225-460c-8405-94fd46430d6b)

**Comment by ran-j** [comment]
![image](https://github.com/leeao/Noesis-Plugins/assets/17410205/af003038-6f21-40d7-87d6-b12528497a0e)
nice, thanks for your work.

Are you planing suport anm files as well ?

**Comment by leeao** [comment]
I have already added support for the animation of Type 1 in private, but I currently do not plan to release it.

**Comment by ran-j** [comment]
Ah ok hahha
